#!/usr/bin/python3

import sys
from thermistor_utils import SH_converter

# Coefficients that result in a match for the lookup table
# in the Glodline GL30 manual.
A, B, C = (0.001125308852122, 0.000234711863267,  0.000000085663516)

conv = SH_converter(A, B, C)

# Resistance from command line.
R=int(sys.argv[1])

# For the current arrangement (divider with 10k fixed R and 5V supply) things go AWOL
# below ~25C because our stupid ADC only operates up to 2.5V. The real fix for this is
# to switch the divider over to the 2.5V supply from the Pi's GPIO header and tweak the
# scaling in the adc code, but for now, this should keep things working by faking a low
# temperature.
FAIL_TEMP=24
if (R is None ) or (R == 0) :
  print("R=%d => no valid temperature, treating as %d." % (R, FAIL_TEMP), file=sys.stderr)
  print("%d" %(FAIL_TEMP))
  exit(0)

# Convert to temp (C).
T=conv.temperature(R)

# For now, show both Celsius and F as Goldline manual lists the latter.
print("R=%d => T=%0.1lfC T=%0.1fF" % (R, T, T*1.8 + 32), file=sys.stderr)
print("%.1lf" % T)

